---
- hosts: all
  name: hello
  become: yes
  gather_facts: false
  tasks:

  - name: Hello
    debug:
      msg: Hello
  
  - name: check passalgo
    shell: bash /tmp/test.sh
    register: passalgo

  - name: create autconfig script
    shell: echo "authconfig --passalgo={{ item }} --update" > /tmp/authconfig.sh
    with_items: "{{ passalgo.stdout_lines }}"

  - name: fetch passalgo script
    fetch:
      src: /tmp/authconfig.sh
      dest: /data

  - name: check dir
    shell: find {{ folder }} -type f
    register: output

  - name: capture output
    shell: ls {{ item }}
    with_items: 
      - "{{ output.stdout_lines }}"
    ignore_errors: yes

  - name: script
    script: "{{ path }}/test.sh"
    args:
      executable: bash
