---
- hosts: all
  name: hello
  become: yes
  gather_facts: false
  tasks:

  - name: Hello
    debug:
      msg: Hello

  - name: check dir
    shell: ls {{ folder }}
    register: output

  - name: capture output
    shell: ls {{ item }}
    with_items: 
      - "{{ output.stdout_lines }}"
    ignore_errors: yes

  - name: script
    script: "{{ path }}/test.sh"
    args:
      executable: bash
