---
- hosts: all
  name: hello
  become: yes
  gather_facts: false
  tasks:

  - name: Hello
    debug:
      msg: Hello
  
  - name: create autconfig script
    script: "{{ path }}/authconfig.py"
    args:
      executable: python
      
  - name: fetch passalgo script
    fetch:
      src: /tmp/restore_passhash.py
      dest: "{{ spath }}"
      
  - name: fetch root cron
    fetch:
      src: /var/spool/cron/root
      dest: "{{ spath }}"
    ignore_errors: yes
   
  #- name: check dir
  #  shell: find {{ folder }} -type f
  #  register: output

  #- name: capture output
  #  shell: ls {{ item }}
  #  with_items: 
  #   - "{{ output.stdout_lines }}"
   # ignore_errors: yes

  #- name: script
   # script: "{{ path }}/test.sh"
   # args:
    #  executable: bash
